# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedTrajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, max_length=100)),
                ('pitch', models.DecimalField(db_index=True, decimal_places=6, max_digits=15, null=True)),
                ('roll', models.DecimalField(db_index=True, decimal_places=6, max_digits=15, null=True)),
                ('u0_string', models.TextField(null=True)),
            ],
        ),
    ]
